### ISSUE TITLE
Use of this from command line or as library?

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/polygon-width#5]
Looks great on a use case I just looked at: 
![image](https://github.com/dabreegster/polygon-width/assets/1825120/5132c4d4-cca4-4d8d-8ad3-b083a9b8bc5e)

Any chance of being able to call this code from the command line or as a library?

Not had a look at the code sorry, probably should!

**Comment by dabreegster** [comment]
I'll make both a CLI (with parallelization + progress bars, intended to handle huge inputs) and expose a library (thinking about bindings) once the output is useful. This a simple case; see some of the built-in examples or issues for cases that break. But hopefully we can work through most of the bugs, get good results, and find quite a lot of use for this!

**Comment by Robinlovelace** [comment]
Awesome. Will close in favour of more specific issues, thanks Dustin!
